"""
config.py

Central configuration for SafeVision AI. All environment-dependent
settings are read here (from a `.env` file via python-dotenv) and exposed
as class attributes on Config, so nothing else in the app hardcodes paths,
secrets, or tunable values.

Usage:
    from config import Config
    app.config.from_object(Config)
    Config.ensure_folders_exist()
"""

import os
from datetime import timedelta
from dotenv import load_dotenv

load_dotenv()


def _env_bool(name, default="0"):
    return os.environ.get(name, default).strip().lower() in ("1", "true", "yes", "on")


class Config:
    # ==========================================
    # PATHS
    # ==========================================
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))

    UPLOAD_FOLDER_IMG = os.path.join(BASE_DIR, 'uploads', 'images')
    UPLOAD_FOLDER_VID = os.path.join(BASE_DIR, 'uploads', 'videos')
    RESULT_FOLDER_IMG = os.path.join(BASE_DIR, 'results', 'annotated_images')
    RESULT_FOLDER_VID = os.path.join(BASE_DIR, 'results', 'annotated_videos')
    REPORT_FOLDER = os.path.join(BASE_DIR, 'results', 'reports')
    LOG_FOLDER = os.path.join(BASE_DIR, 'logs')
    DATABASE_PATH = os.path.join(BASE_DIR, 'database', 'ppe_detection.db')

    MODEL_FILENAME = os.environ.get("SAFEVISION_MODEL_FILENAME", "yolov8_ppe.pt")
    MODEL_PATH = os.path.join(BASE_DIR, 'models', MODEL_FILENAME)

    # ==========================================
    # FACE RECOGNITION (profile photo -> live camera name tagging)
    # ==========================================
    # Where each user's uploaded profile photo is stored (served back to
    # the browser for the profile-page preview / avatar).
    PROFILE_PHOTOS_FOLDER = os.path.join(BASE_DIR, 'uploads', 'profile_photos')

    # Where the trained OpenCV LBPH recognizer + its label map live.
    # Both are auto-generated by utils/face_recognition_helper.py the
    # first time a user uploads a profile photo — nothing to create by hand.
    FACE_MODEL_DIR = os.path.join(BASE_DIR, 'models')
    FACE_SAMPLES_DIR = os.path.join(FACE_MODEL_DIR, 'face_samples')
    FACE_RECOGNIZER_PATH = os.path.join(FACE_MODEL_DIR, 'face_recognizer.yml')
    FACE_LABELS_PATH = os.path.join(FACE_MODEL_DIR, 'face_labels.json')

    # LBPH prediction returns a *distance* (lower = more confident match).
    # Anything above this threshold is reported as "Unknown" rather than
    # risking a wrong name on the live feed. Tune via .env if you're
    # getting too many/too few matches for your camera + lighting — watch
    # the "distance=" values printed by recognize_faces_in_frame() (see
    # DEBUG_LOG_CONFIDENCE in face_recognition_helper.py) to pick a good
    # value: it should sit comfortably above your own typical match
    # distance but below random strangers' distances.
    FACE_RECOGNITION_CONFIDENCE_THRESHOLD = float(
        os.environ.get("FACE_RECOGNITION_CONFIDENCE_THRESHOLD", 75)
    )

    # --- DNN face DETECTOR (separate from the LBPH RECOGNIZER above) ---
    # Optional but strongly recommended: OpenCV's SSD-based face detector,
    # far more reliable than the Haar cascade fallback for off-angle faces
    # and faces that are small/far from the camera. Automatically used
    # once these two files are downloaded into models/ — see the one-time
    # setup commands in _get_dnn_net() inside
    # utils/face_recognition_helper.py. If they're missing, detection
    # silently falls back to the Haar cascade (shorter range, frontal-only).
    FACE_DETECTOR_PROTOTXT_PATH = os.path.join(FACE_MODEL_DIR, 'deploy.prototxt')
    FACE_DETECTOR_MODEL_PATH = os.path.join(
        FACE_MODEL_DIR, 'res10_300x300_ssd_iter_140000_fp16.caffemodel'
    )
    # Minimum DNN detector confidence (0-1) to count as a face at all —
    # this is a *detection* threshold (is there a face here?), separate
    # from FACE_RECOGNITION_CONFIDENCE_THRESHOLD above (whose face is it?).
    # Lower it (e.g. 0.35) if distant/angled faces aren't being detected at
    # all; raise it if you're getting false-positive face boxes.
    FACE_DETECTION_CONFIDENCE = float(os.environ.get("FACE_DETECTION_CONFIDENCE", 0.5))

    # ==========================================
    # FLASK CORE
    # ==========================================
    SECRET_KEY = os.environ.get("SAFEVISION_SECRET_KEY", "change-this-in-production")
    DEBUG = _env_bool("SAFEVISION_DEBUG", "1")

    # ==========================================
    # SESSION / COOKIE HARDENING
    # ==========================================
    SESSION_IDLE_TIMEOUT_MINUTES = int(os.environ.get("SESSION_IDLE_TIMEOUT_MINUTES", 30))
    PERMANENT_SESSION_LIFETIME = timedelta(minutes=SESSION_IDLE_TIMEOUT_MINUTES)
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    # Only true once actually served over HTTPS (see .env: SAFEVISION_HTTPS)
    SESSION_COOKIE_SECURE = _env_bool("SAFEVISION_HTTPS", "0")

    # CSRF token lifetime is tied to the session's own idle timeout instead
    # of Flask-WTF's default 1-hour clock — see utils/security.py for why.
    WTF_CSRF_TIME_LIMIT = None

    # ==========================================
    # UPLOAD LIMITS
    # ==========================================
    MAX_CONTENT_LENGTH = int(os.environ.get("MAX_CONTENT_LENGTH_MB", 50)) * 1024 * 1024

    # ==========================================
    # GUEST / DEMO ACCOUNT
    # ==========================================
    GUEST_USERNAME = os.environ.get("SAFEVISION_GUEST_USERNAME", "guest")
    GUEST_PASSWORD = os.environ.get("SAFEVISION_GUEST_PASSWORD", "guest12345")

    # ==========================================
    # YOLO MODEL / INFERENCE SETTINGS
    # ==========================================
    CONF_THRESHOLD = float(os.environ.get("CONF_THRESHOLD", 0.25))
    INFERENCE_IMGSZ = int(os.environ.get("INFERENCE_IMGSZ", 640))

    @classmethod
    def ensure_folders_exist(cls):
        """Call once at startup — creates every folder the app writes to."""
        for folder in [cls.UPLOAD_FOLDER_IMG, cls.UPLOAD_FOLDER_VID, cls.RESULT_FOLDER_IMG,
                       cls.RESULT_FOLDER_VID, cls.REPORT_FOLDER, cls.LOG_FOLDER,
                       cls.PROFILE_PHOTOS_FOLDER, cls.FACE_SAMPLES_DIR,
                       os.path.dirname(cls.DATABASE_PATH), os.path.dirname(cls.MODEL_PATH)]:
            os.makedirs(folder, exist_ok=True)